# Generated by Django 4.0 on 2022-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='price'),
        ),
    ]
