# Generated by Django 4.0.1 on 2022-01-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='status'),
        ),
    ]
