# Generated by Django 4.0.1 on 2022-01-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='civil_status',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='civil_status'),
        ),
    ]
