# Generated by Django 4.0.1 on 2022-02-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star_1',
            field=models.IntegerField(blank=True, default=0, verbose_name='star_1'),
        ),
        migrations.AddField(
            model_name='user',
            name='star_2',
            field=models.IntegerField(blank=True, default=0, verbose_name='star_2'),
        ),
        migrations.AddField(
            model_name='user',
            name='star_3',
            field=models.IntegerField(blank=True, default=0, verbose_name='star_3'),
        ),
        migrations.AddField(
            model_name='user',
            name='star_4',
            field=models.IntegerField(blank=True, default=0, verbose_name='star_4'),
        ),
        migrations.AddField(
            model_name='user',
            name='star_5',
            field=models.IntegerField(blank=True, default=0, verbose_name='star_5'),
        ),
    ]
