# Generated by Django 4.0.1 on 2022-02-02 09:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_star_1_user_star_2_user_star_3_user_star_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signed_image',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=users.models.nameFile, verbose_name='signed_image'),
        ),
    ]
