# Generated by Django 4.0.1 on 2022-02-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_city_of_user_mailing_address_user_state_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_signed',
            field=models.CharField(blank=True, max_length=255, verbose_name='name_signed'),
        ),
    ]
