# Generated by Django 4.0 on 2022-01-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='reference_type')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
