# Generated by Django 4.0.1 on 2022-01-24 07:19

from django.db import migrations, models
import swap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('listing_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('milleage', models.CharField(blank=True, max_length=255, null=True, verbose_name='milleage')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='color')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('fuel_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='fuel_type')),
                ('image', models.ImageField(default='uploads/users_placeholder.png', upload_to=swap.models.nameFile, verbose_name='image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
