# Generated by Django 4.0.1 on 2022-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='listing_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_id'),
        ),
    ]
