# Generated by Django 4.0.1 on 2022-01-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='listing_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='listing_id'),
        ),
    ]
