# Generated by Django 4.0 on 2022-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='price')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='brand')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='year')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model')),
                ('condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='condition')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='color')),
                ('variant', models.CharField(blank=True, max_length=255, null=True, verbose_name='variant')),
                ('body_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='body_type')),
                ('milleage', models.CharField(blank=True, max_length=255, null=True, verbose_name='milleage')),
                ('isBid', models.BooleanField(blank=True, default=False, verbose_name='isBid')),
                ('isSell', models.BooleanField(blank=True, default=False, verbose_name='isSell')),
                ('isSwap', models.BooleanField(blank=True, default=False, verbose_name='isSwap')),
                ('transmission', models.CharField(blank=True, max_length=255, null=True, verbose_name='transmission')),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='plate_number')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='descriptions')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
