# Generated by Django 4.0 on 2022-01-16 15:51

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=listing.models.nameFile, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id'),
        ),
    ]
