# Generated by Django 4.0 on 2022-01-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_image_listing_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='numberOfSeats',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='numberOfSeats'),
        ),
    ]
