# Generated by Django 4.0 on 2022-01-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_numberofseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fuel_type'),
        ),
    ]
