# Generated by Django 4.0.1 on 2022-01-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='current_bid'),
        ),
    ]
