# Generated by Django 4.0.1 on 2022-01-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_bidding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='start_bidding'),
        ),
    ]
