# Generated by Django 4.0.1 on 2022-01-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_listing_start_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='live_bidding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='live_bidding'),
        ),
    ]
