# Generated by Django 4.0.1 on 2022-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_listing_live_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
    ]
