# Generated by Django 4.0.1 on 2022-01-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_listing_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='label',
        ),
    ]
