# Generated by Django 4.0.1 on 2022-01-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_id')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_name')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
