# Generated by Django 4.0.1 on 2022-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='start_bidding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='start_bidding'),
        ),
    ]
