# Generated by Django 4.0.1 on 2022-01-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactions_start_bidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='start_bidding',
        ),
    ]
